INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('ELETRONICOS','01/10/20');
INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('PAPEL E CIA','12/04/21');
INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('ENFERMAGEM','12/04/19');
INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('ROUPAS','12/04/21');