INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('ELETRONICOS','01/10/20');
INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('PAPEL E CIA','12/04/21');
INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('ENFERMAGEM','12/04/19');
INSERT INTO CATEGORIA(DESCRICAO,DATA_CADASTRO) VALUES ('ROUPAS','12/04/21');



INSERT INTO PRODUTO(DESCRICAO,UNIDADE_MEDIDA,VALOR_UNITARIO,STATUS)VALUES('Computador','Quilo',2000.6,0);
INSERT INTO PRODUTO(DESCRICAO,UNIDADE_MEDIDA,VALOR_UNITARIO,STATUS)VALUES('Celular','Quilo',2000.6,0);
INSERT INTO PRODUTO(DESCRICAO,UNIDADE_MEDIDA,VALOR_UNITARIO,STATUS)VALUES('Microfone','Quilo',2000.6,1);
INSERT INTO PRODUTO(DESCRICAO,UNIDADE_MEDIDA,VALOR_UNITARIO,STATUS)VALUES('TV','Quilo',2000.6,0);
INSERT INTO PRODUTO(DESCRICAO,UNIDADE_MEDIDA,VALOR_UNITARIO,STATUS)VALUES('Relogio','Quilo',2000.6,1);